---
# Run webportal docker-compose

- name: Restart docker-compose
  block:

    - name: Stop docker-compose
      community.docker.docker_compose:
        project_src: "{{ webportal_dir }}"
        state: absent

    - name: Run `docker-compose up`
      community.docker.docker_compose:
        project_src: "{{ webportal_dir }}"
        build: yes
      register: output

  become: true
  become_user: "{{ webportal_user }}"