---
# tasks file for skynetlabs.skynet_webportal

# Requirements:
# - docker
# - Docker and docker-compose SDK for Python (python3-pip)
# - git

- name: Check supported OS and version
  assert:
    that:
      - ansible_distribution|lower == 'debian' and ansible_distribution_version == '10'
    fail_msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} is not yet supported by this role"

- name: Run "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 900
  become: True

# Set file limits. siad stores a lot of files so we need to adjust so server
# doesn't choke up
- name: Set filelimits
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    regexp: '^{{ webportal_user }}.*nofile'
    line: '{{ webportal_user }}             soft    nofile          {{ webportal_user_filelimits }}'
    insertbefore: '^# End of file'
  become: True

# Checkout webportal repo
- name: Checkout webportal repo
  ansible.builtin.git:
    repo: "{{ webportal_repo_url }}"
    dest: "{{ webportal_dir }}"

# Config git
- name: Config git
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop: "{{ webportal_git_config }}"