---
# Setup server

- name: Run "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 900

- name: Install sudo, python3-pip
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - sudo
    - python3-pip

- name: Install Docker SDK and docker-compose SDK for Python
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - docker-compose

- name: Set timezone
  community.general.timezone:
    name: "{{ webportal_server_timezone }}"
  when: webportal_server_set_timezone