---
# Configure user settings

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add skynet portal user
  ansible.builtin.user:
    name: "{{ webportal_user }}"
    groups:
      - sudo
      - docker

- name: Checkout skynet-webportal repo locally
  local_action:
    module: ansible.builtin.git
    repo: "{{ skynet_webportal_repo_url }}"
    dest: "{{ local_skynet_webportal_repo }}"
    version: "{{ skynet_webportal_version }}"
  run_once: True
  become: False

- name: Add SSH keys from skynet-webportal repo to webportal user
  ansible.posix.authorized_key:
    user: "{{ webportal_user }}"
    state: present
    key: "{{ item }}"
  loop: "{{ lookup('file', '{{ local_skynet_webportal_repo }}/setup-scripts/support/authorized_keys').splitlines() }}"

# Set file limits. siad stores a lot of files so we need to adjust so server
# doesn't choke up
- name: Set filelimits
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    regexp: '^user.*nofile'
    line: 'user             soft    nofile          {{ webportal_user_filelimits }}'
    insertbefore: '^# End of file'
  when: webportal_user_set_filelimits