---
# Setup Skynet webportal

- name: Create webportal directory
  ansible.builtin.file:
    path: "{{ webportal_dir }}"
    state: directory
    owner: "{{ webportal_user }}"
    group: "{{ webportal_user }}"
    mode: '0700'

- name: Copy webportal .env file
  copy:
    content: "{{ webportal_host_env_content }}"
    dest: "{{ webportal_dir }}/.env"
    owner: "{{ webportal_user }}"
    group: "{{ webportal_user }}"
    mode: '0600'

- name: Checkout skynet-webportal repo
  local_action:
    module: ansible.builtin.git
    repo: "{{ skynet_webportal_repo_url }}"
    dest: "{{ temp_skynetlabs_git_webportal }}"
    version: "{{ skynet_webportal_version }}"
  run_once: true
  become: false

- name: Copy docker-compose.yml file
  copy:
    src: "{{ temp_skynetlabs_git_webportal }}/docker-compose.yml"
    dest: "{{ webportal_dir }}"
    owner: "{{ webportal_user }}"
    group: "{{ webportal_user }}"
    mode: '0600'

- name: Sync docker and packages directories
  ansible.posix.synchronize:
    src: "{{ temp_skynetlabs_git_webportal }}/{{ item }}"
    dest: "{{ webportal_dir }}"
    owner: no
    group: no
    delete: yes
    recursive: yes
  loop:
    - docker
    - packages

- name: Tighten file permissions
  file:
    dest: "{{ webportal_dir }}"
    owner: "{{ webportal_user }}"
    group: "{{ webportal_user }}"
    mode: u=rwX,g=,o=
    recurse: yes

- name: Fix for v1.5.5 siac, siad instead of skyc, skyd
  ansible.builtin.lineinfile:
    path: "{{ webportal_dir }}/docker/sia/Dockerfile"
    regexp: '^COPY .* /usr/bin/{{ item.binary }}$'
    line: "COPY --from=sia-builder /go/bin/{{ item.pattern }} /usr/bin/{{ item.binary }}"
  loop:
    - { binary: "siac", pattern: "s??c"}
    - { binary: "siad", pattern: "s??d"}

- name: Check if MongoDB was initialized
  stat:
    path: "{{ webportal_docker_data_mongo_dir }}/db"
  register: mongo_db_dir

- name: Initialize MongoDB once
  block:

    - name: Create MongoDB data directory
      file:
        path: "{{ webportal_docker_data_mongo_dir }}"
        state: directory

    - name: Upload MongoDB keyfile
      copy:
        content: "{{ webportal_mongo_mgkey_content }}"
        dest: "{{ webportal_docker_data_mongo_dir }}/mgkey"
    
    - name: Initialize MongoDB with admin username and password
      community.docker.docker_container:
        name: mongo
        image: mongo:4.4.1
        command: --keyFile=/data/mgkey --replSet=skynet
        state: present
        recreate: yes
        env:
          MONGO_INITDB_ROOT_USERNAME: "{{ webportal_mongo_init_username }}"
          MONGO_INITDB_ROOT_PASSWORD: "{{ webportal_mongo_init_password }}}"
        exposed_ports:
          - 27017:27017
        volumes:
          - "{{ webportal_docker_data_mongo_dir }}/db:/data/db"
          - "{{ webportal_docker_data_mongo_dir }}/mgkey:/data/mgkey"
    
    #xxx test failure, then remove
    - name: Force a failure during recovery
      ansible.builtin.command: /bin/false
    
  # Remove mongo/db if the block fails, so the block can execute on next run
  rescue:
    - name: Remove mongo/db directory on initialization failure
      ansible.builtin.file:
        path: "{{ webportal_docker_data_mongo_dir }}/db"
        state: absent

    - name: Force a failure after recovery
      ansible.builtin.command: /bin/false
  
  when: mongo_db_dir.stat.exists == false

- name: Restart docker-compose
  block:

    - name: Stop docker-compose
      community.docker.docker_compose:
        project_src: "{{ webportal_dir }}"
        state: absent

    # xxx check all flags
    - name: Run `docker-compose up`
      community.docker.docker_compose:
        project_src: "{{ webportal_dir }}"
        build: yes
      register: output

  become: true
  become_user: "{{ webportal_user }}"